// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editshippinginEF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editshippinginEF));
        
        string IMigrationMetadata.Id
        {
            get { return "201605190427142_edit shipping in EF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
